# Generated by Django 5.0.1 on 2024-01-20 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_id', models.CharField(max_length=100, unique=True, verbose_name='آیدی سوال')),
                ('name', models.CharField(max_length=50, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('question_count', models.IntegerField(default=1, verbose_name='تعداد سوال')),
                ('image', models.ImageField(upload_to='images/questions/', verbose_name='تصویر سوال')),
                ('price', models.CharField(max_length=100, verbose_name='هزینه پرداخت شده')),
                ('is_done', models.BooleanField(default=False, verbose_name='پاسخ داد شده / نشده')),
                ('date_sent', models.DateTimeField(verbose_name='تاریخ ارسال')),
            ],
            options={
                'verbose_name': 'سوال',
                'verbose_name_plural': 'سوالات',
                'ordering': ['-date_sent'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/questions/', verbose_name='جواب سوال')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='answers', to='questions.question')),
            ],
            options={
                'verbose_name': 'جواب سول',
                'verbose_name_plural': 'جواب سوالات',
            },
        ),
    ]
