# Generated by Django 5.0.1 on 2024-01-20 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='short_id',
            field=models.CharField(editable=False, max_length=100, unique=True, verbose_name='آیدی سوال'),
        ),
    ]
