# Generated by Django 5.0.1 on 2024-01-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_alter_answer_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_count',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15')], default=1, max_length=100, verbose_name='تعداد سوال'),
        ),
    ]
