# Generated by Django 5.0.1 on 2024-01-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_alter_question_question_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_count',
            field=models.CharField(choices=[('1', 1)], default=1, max_length=100, verbose_name='تعداد سوال'),
        ),
    ]
