# Generated by Django 5.0.1 on 2024-01-20 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_alter_question_question_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_count',
            field=models.IntegerField(default=1, verbose_name='تعداد سوال'),
        ),
    ]
