# Generated by Django 5.0.1 on 2024-01-20 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_alter_question_question_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.BigIntegerField(default=0, verbose_name='قیمت(تومان)')),
                ('q_count', models.IntegerField(default=10, verbose_name='حداکثر تعداد درخواست حل مسئله')),
            ],
            options={
                'verbose_name': 'تنظیمات بخش حل مسئله',
                'verbose_name_plural': 'تنظیمات بخش حل مسئله',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='question_title',
            field=models.CharField(default='', max_length=100, verbose_name='عنوان سوال'),
        ),
    ]
