# Generated by Django 5.0.1 on 2024-01-20 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_questionprice_question_question_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='عنوان سوال')),
            ],
            options={
                'verbose_name': 'عنوان',
                'verbose_name_plural': 'عنوان های سوالات',
            },
        ),
    ]
