# Generated by Django 5.0.1 on 2024-01-21 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0012_question_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-date_sent'], 'verbose_name': 'سوال', 'verbose_name_plural': 'سبد سوالات'},
        ),
        migrations.RemoveField(
            model_name='question',
            name='is_done',
        ),
        migrations.AddField(
            model_name='question',
            name='is_pay',
            field=models.BooleanField(default=False, verbose_name='پرداخت شده / نشده'),
        ),
        migrations.CreateModel(
            name='QuestionComplete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل کاربر')),
                ('question_title', models.CharField(max_length=100, verbose_name='عنوان سوال')),
                ('question_file', models.ImageField(upload_to='image/question_complete/', verbose_name='تصویر سوال')),
                ('question_count', models.IntegerField(default=0, verbose_name='تعداد سوال')),
                ('price', models.IntegerField(default=0, verbose_name='قیمت کل')),
                ('date_created', models.DateTimeField(verbose_name='تاریخ ایجاد')),
                ('is_answered', models.BooleanField(default=False, verbose_name='جواب داده شده/ نشده')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='questions.question', verbose_name='سوال')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='comp_question', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سوال',
                'verbose_name_plural': 'سوالات پرداخت شده',
                'ordering': ['-date_created'],
            },
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='questions.questioncomplete'),
        ),
    ]
