# Generated by Django 5.0.1 on 2024-01-21 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0013_alter_question_options_remove_question_is_done_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='questioncomplete',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question', verbose_name='سوال'),
        ),
        migrations.AlterField(
            model_name='questioncomplete',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comp_question', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
