# Generated by Django 4.2.9 on 2024-01-22 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_user_password_rest_tokrn_customuser_user_password_rest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_password_rest_token',
            field=models.CharField(blank=True, editable=False, max_length=32, null=True, unique=True, verbose_name='توکن تغییر رمز عبور'),
        ),
    ]
