# Generated by Django 5.0.1 on 2024-01-20 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام مالک سایت')),
                ('owner_description', models.TextField(blank=True, null=True, verbose_name='درباره مالک سایت')),
                ('site_name', models.CharField(max_length=100, verbose_name='عنوان سایت')),
                ('site_url', models.URLField(help_text='مثال: https://google.com/')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره تماس')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('site_logo', models.ImageField(blank=True, null=True, upload_to='images/logos/', verbose_name='لوگوی سایت')),
            ],
            options={
                'verbose_name': 'تنظیم',
                'verbose_name_plural': 'تنظیمات سایت',
                'ordering': ['-id'],
            },
        ),
    ]
