# Generated by Django 5.0.1 on 2024-01-20 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.BigIntegerField(default=0, verbose_name='قیمت(تومان)')),
            ],
            options={
                'verbose_name': 'قیمت هر مسئله',
                'verbose_name_plural': 'قیمت هر مسئله',
            },
        ),
    ]
