# Generated by Django 5.0.1 on 2024-01-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_questionprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionprice',
            name='count',
            field=models.IntegerField(default=10, verbose_name='حداکثر تعداد درخواست حل مسئله'),
        ),
    ]
