# Generated by Django 5.0.1 on 2024-01-20 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0003_questionprice_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionprice',
            options={'verbose_name': 'تنظیمات بخش حل مسئله', 'verbose_name_plural': 'تنظیمات بخش حل مسئله'},
        ),
        migrations.RenameField(
            model_name='questionprice',
            old_name='count',
            new_name='q_count',
        ),
    ]
