# Generated by Django 5.0.1 on 2024-01-20 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0004_alter_questionprice_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionPrice',
        ),
    ]
