# Generated by Django 5.0.1 on 2024-01-21 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0005_delete_questionprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.TextField(verbose_name='کلمات کلیدی')),
                ('descriptions', models.TextField(verbose_name='توضیحات درباره سایت')),
            ],
            options={
                'verbose_name': 'سئو',
                'verbose_name_plural': 'سئو سایت',
            },
        ),
    ]
