# Generated by Django 5.0.1 on 2024-01-21 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0006_seo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='owner_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/owner_img/', verbose_name='تصویر مالک سایت'),
        ),
    ]
