# Generated by Django 5.0.1 on 2024-01-21 03:37

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0007_sitesetting_owner_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام و نام خانوادگی')),
                ('description', ckeditor.fields.RichTextField(verbose_name='درباره من')),
                ('phone', models.CharField(max_length=100, verbose_name='شماره تماس')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
            ],
            options={
                'verbose_name': 'درباره من',
                'verbose_name_plural': 'درباره من',
            },
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='مثال: instagram', max_length=100, verbose_name='نام شبکه اجتماعی')),
                ('url', models.URLField(help_text='مثال: https://instagram.com/username/', verbose_name='لینک')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_settings.aboutme', verbose_name='مدل درباره من')),
            ],
            options={
                'verbose_name': 'شبکه',
                'verbose_name_plural': 'شبکه ها',
            },
        ),
    ]
