# Generated by Django 5.0.1 on 2024-01-21 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0008_aboutme_socialnetwork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialnetwork',
            name='name',
            field=models.CharField(blank=True, help_text='مثال: instagram', max_length=100, null=True, verbose_name='نام شبکه اجتماعی'),
        ),
        migrations.AlterField(
            model_name='socialnetwork',
            name='url',
            field=models.URLField(blank=True, help_text='مثال: https://instagram.com/username/', null=True, verbose_name='لینک'),
        ),
    ]
