# Generated by Django 5.0.1 on 2024-01-20 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_price_completeorder'),
        ('products', '0003_product_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completeorder',
            name='order',
        ),
        migrations.AddField(
            model_name='completeorder',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='products.product', verbose_name='محصول'),
        ),
    ]
