# Generated by Django 5.0.1 on 2024-01-20 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان محصول')),
                ('description', models.TextField(verbose_name='توضیحات کوتاه محصول')),
                ('image', models.ImageField(upload_to='images/', verbose_name='تصویر محصول')),
                ('price', models.BigIntegerField(default=0, verbose_name='قیمت محصول')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
    ]
