# Generated by Django 5.0.1 on 2024-01-20 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.BigIntegerField(default=0, verbose_name='قیمت محصول(تومان)'),
        ),
    ]
