# Generated by Django 5.0.1 on 2024-01-20 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='file',
            field=models.FileField(default=None, upload_to='products/files/', verbose_name='فایل (محصول)'),
        ),
    ]
