# Generated by Django 5.0.1 on 2024-01-21 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id'], 'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
    ]
